### ISSUE TITLE
Add support for PHP 5.5, PHP 5.6

### ISSUE THREAD

**Issue by rkmax** [laruence/php-lua#11]

**Comment by hjanuschka** [comment]
with this commit - you should be able to build with 5.5 and 5.6

https://github.com/hjanuschka/php-lua/commit/0656d3782c5710c2287ef27cd6f0a02ee4ea8eae
could you be more specific?


    =====================================================================
    PHP         : /tmp/php5.5-bin/bin/php 
    PHP_SAPI    : cli
    PHP_VERSION : 5.5.22-dev
    ZEND_VERSION: 2.5.0
    PHP_OS      : Linux - Linux ip-172-31-14-228 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64
    INI actual  : /home/admin/tmp/php-lua/tmp-php.ini
    More .INIs  :  
    CWD         : /home/admin/tmp/php-lua
    Extra dirs  : 
    VALGRIND    : Not used
    =====================================================================
    TIME START 2015-02-02 16:07:24
    =====================================================================
    PASS Basic lua check [tests/001.phpt] 
    PASS Set and read properties [tests/002.phpt] 
    PASS Call lua functions [tests/003.phpt] 
    PASS Type conversion from lua to PHP [tests/004.phpt] 
    PASS Lua phpinfo() block [tests/005.phpt] 
    PASS Lua::include() [tests/006.phpt] 
    PASS Lua return function [tests/007.phpt] 
    PASS register php function to lua [tests/008.phpt] 
    PASS Bug (eval and include compute wrong return value number) [tests/009.phpt] 
    PASS LuaClosure exception [tests/010.phpt] 
    PASS register invalid php callback to lua [tests/011.phpt] 
    PASS Lua::include() with error codes [tests/012.phpt] 
    PASS PHP Closures from Lua [tests/013.phpt] 
    PASS Bug #65097 (nApplyCount release missing) [tests/bug65097.phpt] 
    =====================================================================
    TIME END 2015-02-02 16:07:24
    
    =====================================================================
    PHP         : /tmp/php5.6-bin/bin/php 
    PHP_SAPI    : cli
    PHP_VERSION : 5.6.6-dev
    ZEND_VERSION: 2.6.0
    PHP_OS      : Linux - Linux ip-172-31-14-228 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64
    INI actual  : /home/admin/tmp/php-lua/tmp-php.ini
    More .INIs  :  
    CWD         : /home/admin/tmp/php-lua
    Extra dirs  : 
    VALGRIND    : Not used
    =====================================================================
    TIME START 2015-02-02 16:09:35
    =====================================================================
    PASS Basic lua check [tests/001.phpt] 
    PASS Set and read properties [tests/002.phpt] 
    PASS Call lua functions [tests/003.phpt] 
    PASS Type conversion from lua to PHP [tests/004.phpt] 
    PASS Lua phpinfo() block [tests/005.phpt] 
    PASS Lua::include() [tests/006.phpt] 
    PASS Lua return function [tests/007.phpt] 
    PASS register php function to lua [tests/008.phpt] 
    PASS Bug (eval and include compute wrong return value number) [tests/009.phpt] 
    PASS LuaClosure exception [tests/010.phpt] 
    PASS register invalid php callback to lua [tests/011.phpt] 
    PASS Lua::include() with error codes [tests/012.phpt] 
    PASS PHP Closures from Lua [tests/013.phpt] 
    PASS Bug #65097 (nApplyCount release missing) [tests/bug65097.phpt] 
    =====================================================================
    TIME END 2015-02-02 16:09:36

**Comment by rkmax** [comment]
thanks @hjanuschka
