### ISSUE TITLE
PHP 7: Lua::eval(): unsupported type `unknown' for lua

### ISSUE THREAD

**Issue by vladimir-yuldashev** [laruence/php-lua#20]

**Comment by laruence** [comment]
is there any test script to reproduce this?

**Comment by glenwong** [comment]
I modified one of the phpt tests to reproduce this issue.

```
<?php 
$l = new lua();
class A {
    public static function intro($foo, $bar) {
        throw new InvalidArgumentException("Invalid Argument");
        echo $foo, $bar;
  }
}   
    
$l->registerCallback("callphp", array("A", "intro")); 
try {
$l->eval(<<<CODE
    callphp("foo", "bar");
CODE
);
} catch (Exception $e) {
    var_dump($e->getMessage());
}
?>
```

In php7 this blows up with `Fatal error: Lua::eval(): unsupported type `unknown' for lua` but in php54 the exception is caught and just prints `string(16) "Invalid Argument"`

**Comment by laruence** [comment]
this should be fixed, I will make a release soon, thanks
