### ISSUE TITLE
Boolean FALSE is always TRUE

### ISSUE THREAD

**Issue by JohnKiller** [laruence/php-lua#22]
`$lua = new Lua();
$lua->assign('TEST', false);
$result = $lua->eval('return TEST');
var_dump($result);`

This incorrectly returns `bool(true)`

This also happens when returning value from PHP functions using RegisterCallback

**Comment by laruence** [comment]
it should be fixed. thanks

**Comment by JohnKiller** [comment]
Thank you for the fast fix. Will this be released in PECL?

**Comment by laruence** [comment]
@JohnKiller I will probably do a release this weekend, thanks for reporting :)
