### ISSUE TITLE
php 7.0.8 Segmentation faults

### ISSUE THREAD

**Issue by kenkit** [laruence/php-lua#25]
`[ 7160.978673] traps: php[1197] general protection ip:7f2c77cc5eae sp:7ffe44c64a10 error:0 in liblua5.3.so.0.0.0[7f2c77cb0000+35000]
[ 7329.306544] traps: php[5597] general protection ip:7fd50d8c5eae sp:7fff4bb9f8a0 error:0 in liblua5.3.so.0.0.0[7fd50d8b0000+35000]
[ 7526.096608] traps: php[7753] general protection ip:7f68462c5eae sp:7ffc8061ad20 error:0 in liblua5.3.so.0.0.0[7f68462b0000+35000]
[ 8449.318540] traps: php[10576] general protection ip:7f2891ac5eae sp:7fff650441d0 error:0 in liblua5.3.so.0.0.0[7f2891ab0000+35000]
[ 8918.139754] traps: php[12736] general protection ip:7fa14f8c5eae sp:7ffea00fb1d0 error:0 in liblua5.3.so.0.0.0[7fa14f8b0000+35000]
[ 9903.623422] traps: php[15253] general protection ip:7fbc9eac5eae sp:7ffeffead5c0 error:0 in liblua5.3.so.0.0.0[7fbc9eab0000+35000]
[11121.292869] traps: php[23359] general protection ip:7fe780ac5eae sp:7fff89aca970 error:0 in liblua5.3.so.0.0.0[7fe780ab0000+35000]`

**Comment by laruence** [comment]
do you have a reproducible script or codes?

**Comment by kenkit** [comment]
nop but this happens on all versions of php lua, even the one installed via apt-get.
It happens when you try running any lua code from php I don't know why ?
My best guess is some compatibilty between lua 5.3 and php7

**Comment by kenkit** [comment]
Can you try building on the latest version of php and lua to see if it will work, maybe I did something wrong ?

**Comment by laruence** [comment]
sorry, I can not reproduce this:
```
$ /home/huixinchen/local/php7/bin/php -d extension=lua.so -i | grep lua
PHP Warning:  Module 'lua' already loaded in Unknown on line 0
Additional .ini files parsed => /home/huixinchen/local/php7/conf.d/lua.ini,
lua
lua support => enabled
lua extension version => 2.0.3-dev
lua release => Lua 5.3.4
lua copyright => Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
lua authors => R. Ierusalimschy, L. H. de Figueiredo, W. Celes
```

all tests passes here.

**Comment by sgolemon** [comment]
Hard to say if this is related or not, but https://github.com/laruence/php-lua/pull/35 fixes a segfault.
